Lab 1: Tensor Manipulation - 텐서 조작
---

## Imports

In [8]:
import numpy as np
import torch

## NumPy Review

### 1D Array with NumPy

In [9]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [10]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [11]:
print('t[0] t[1] t[-1]  =', t[0], t[1], t[-1])   #Element
print('t[2:5] t[4:-1]   =', t[2:5], t[4:-1])       #Slicing
print('t[:2] t[3:]      =', t[:2], t[3:])

t[0] t[1] t[-1]  = 0.0 1.0 6.0
t[2:5] t[4:-1]   = [2. 3. 4.] [4. 5.]
t[:2] t[3:]      = [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [12]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [13]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


## PyTorch

### 1D Array with PyTorch

In [14]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [15]:
print(t.dim())  #rank
print(t.shape)  #shape
print(t.size()) #same as t.shape (shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [16]:
t = torch.FloatTensor([[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.],
                        [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [17]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Shape, Rank, Axis

In [18]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                        [[13, 14, 15, 16],
                         [17, 18, 19, 20],
                         [21, 22, 23, 24]]
                         ]])

In [19]:
print(t.dim())
print(t.size())

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch - 자주 쓰이는 연산자

### Mul vs Matmul

In [20]:
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1 #내적

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) #요소끼리 곱

-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Broadcasting - 브로드캐스팅
*부주의한 broadcasting 사용은 코드를 디버그하기 어렵게 만듦.

In [24]:
#Same shape
m1 = torch.FloatTensor([[3, 3]]) #1 x 2
m2 = torch.FloatTensor([[2, 2]]) #1 x 2
print(m1 + m2)

tensor([[5., 5.]])


In [29]:
#Vector + scalar
m1 = torch.FloatTensor([[1, 2]]) #1 x 2
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [34]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # 2 x 1
m2 = torch.FloatTensor([[3], [4]]) #1 x 2
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean - 평균

In [35]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [37]:
#정수에 mean()을 사용할 수 없음
t = torch.LongTensor([1, 2])
try:
  print(t.mean())
except Exception as e:
  print(e)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [41]:
#더 높은 차원에서의 mean
t = torch.FloatTensor([[1,2], [3,4]]) #2 x 2
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [42]:
print(t.mean())
print(t.mean(dim=0)) #첫 번째 차원(행)으로 합친 후 평균
print(t.mean(dim=1)) #두 번째 차원(열)으로 합친 후 평균
print(t.mean(dim=-1)) #마지막 차원(열)으로 합친 후 평균

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum - 합

In [44]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [46]:
print(t.sum())
print(t.sum(dim=0)) #첫번째 차원(행)으로 합침
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax - 최대와 최댓값의 인덱스

In [47]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [48]:
print(t.max()) #최댓값

tensor(4.)


In [50]:
print(t.max(dim=0)) #행을 합했을 때 최댓값과 그 값의 인덱스 반환
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [51]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View - 모양바꾸기
*어렵지만 중요함

In [52]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [53]:
print(ft.view([-1, 3])) 
print(ft.view([-1, 3]).shape) # -1은 4로 계산되어서 4 * 3 = 2 * 2* 3 = 12를 만족시키게 됨.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [55]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) #4 * 1 * 3 = 2 * 2 * 3 = 12

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze - 크기가 1인 차원을 제거

In [56]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [89]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [58]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [59]:
print(ft.unsqueeze(0)) #0 means 'dim = 0'
print(ft.unsqueeze(0).shape) #0번 차원에 1이 추가됨

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [60]:
print(ft.view(1, -1)) #unsqueeze의 효과를 냄
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [61]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [62]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting - 형변환

In [64]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [66]:
print(lt.float())

tensor([1., 2., 3., 4.])
<built-in method type of Tensor object at 0x7f600e8308f0>


In [68]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [69]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### concatenation

In [70]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [74]:
print(torch.cat([x,y], dim = 0))
print(torch.cat([x,y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking - 쌓기

In [75]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [81]:
print(torch.stack([x,y,z])) #dim=0
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [82]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like - 같은 모양의 텐서 만들기

In [83]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [84]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation - 입력을 바꾸는 연산

In [85]:
x = torch.FloatTensor([[1,2], [3,4]])

In [86]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) #x의 값을 바꿈
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Miscellaneous

In [87]:
for x, y in zip([1,2,3], [4,5,6]):
  print(x,y)

1 4
2 5
3 6


In [88]:
for x,y,z in zip([1,2,3], [4,5,6], [7,8,9]):
  print(x,y,z)

1 4 7
2 5 8
3 6 9
