# PyTorch - [torch.Tensor.scatter_()](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_)

```python
Tensor.scatter_(dim, index, src, reduce=Nune) -> Tensor
```
언더바가 붙었으므로 텐서를 업데이트하는 In-place 메소드이다.  
파라미터로 주어진 `index`에 맞게 `src`의 값을 `tensor`(self)에 넣어주는 역할을 한다.
  
예를 들어 3차원 텐서라면 다음과 같이 업데이트 한다.
```python
tensor [index[i][j][k]] [j][k] = src[i][j][k] #if dim == 0
tensor[i] [index[i][j][k]] [k] = src[i][j][k] #if dim == 1
tensor[i][j] [index[i][j][k]]  = src[i][j][k] #if dim == 2
```

## Example

In [ ]:
import torch

In [ ]:
src = torch.arange(1, 11).reshape(2, 5)
print(src)

index0 = torch.tensor([[0, 1, 2, 0], [1, 2, 0, 0]])
index1 = torch.tensor([[0, 2, 3, 4], [2, 1, 3, 4]])

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [ ]:
scatterDim0 = torch.zeros((3, 5), dtype= src.dtype).scatter_(0, index0, src)
print(scatterDim0)

tensor([[1, 0, 8, 9, 0],
        [6, 2, 0, 0, 0],
        [0, 7, 3, 0, 0]])


In [ ]:
scatterDim1 = torch.zeros((3, 5), dtype= src.dtype).scatter_(1, index1, src)
print(scatterDim1)

tensor([[1, 0, 2, 3, 4],
        [0, 7, 6, 8, 9],
        [0, 0, 0, 0, 0]])
